[tools]
1password-cli = "latest"
aws = "latest"
claude = "2.0.71"
direnv = "latest"
gcloud = "latest"
gh = "latest"
gradle = "8.13.0"
gum = "latest"
hugo = "0.145.0"
java = "zulu-21.40.17"
lazydocker = "latest"
lazygit = "latest"
neovim = "0.11.2"
node = "24"
pnpm = "10"
python = "3.11.10"
rust = "latest"
tree-sitter = "latest"
uv = "0.8"
xh = "latest"
yarn = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
